# Generated by Django 4.1.2 on 2022-11-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group'),
        ),
    ]
