# Generated by Django 4.1.2 on 2022-11-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_card_options_alter_cardlist_options_card_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.cardlist'),
        ),
    ]
