# Generated by Django 4.1.2 on 2022-11-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_card_groups'),
        ('api', '0003_alter_card_cardlist'),
    ]

    operations = [
    ]
